# Generated by Django 5.0.2 on 2024-03-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('topic', models.CharField(max_length=100)),
                ('number_of_questions', models.PositiveIntegerField()),
                ('time_of_questions', models.PositiveIntegerField()),
                ('required_score_to_pass', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], max_length=60)),
            ],
        ),
    ]
