# Generated by Django 5.0.2 on 2024-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='заголовок поста')),
                ('description', models.TextField(verbose_name='текст поста')),
                ('author', models.CharField(max_length=60, verbose_name='імя автора')),
                ('date', models.DateField(verbose_name='дата публікації')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
