# Generated by Django 5.0.2 on 2024-02-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=25)),
                ('text_comment', models.TextField(max_length=240, verbose_name='текст коментаря')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='публікації')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'коментарi',
            },
        ),
    ]
