# Generated by Django 5.0.2 on 2024-02-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text_comment',
            new_name='text_comments',
        ),
    ]
